#!/usr/bin/env python3
#
# Intelligent Robotics - Master's Degree in Artificial Intelligence - University of Alicante
# ROS node for robot BLUE navigation.

import sys
import copy
import rospy
import std_msgs.msg
import ackermann_msgs.msg
import geometry_msgs.msg
from nav_msgs.msg import Odometry
import sensor_msgs.msg
from visualization_msgs.msg import Marker, MarkerArray
import sensor_msgs.point_cloud2 as pc2
import tf_conversions
import numpy as np
from math import pi, cos, sin, fabs, sqrt, atan2, tan

#Vehicle specifications
MAX_STEER_ANGLE = 24.0*pi/180.0 # Radians
MAX_SPEED = 1.3    # m/s
MIN_SPEED = 0.6
VEHICLE_LENGHT = 1.05 


class BlueTrajectoryPlanner(object):

    def __init__(self):
        super(BlueTrajectoryPlanner, self).__init__()

        ##ROS node initialization
        rospy.init_node("blue_planner_node", anonymous=True)

        #Parameter initialization
        self.delta_angle=6.0*pi/180.0
        self.delta_sample=0.2
        self.max_sample=1.0
        self.reached_distance=1.0
        self.slow_down_distance=2.0
        self.rate=5

        #TODO Define other parameters needed for the planner.

        # -------------------------------------------------------------------------
        # BLOCK 1: Planner parameters.
        # These parameters define safety margins, trajectory scoring weights, and
        # whether localization is obtained from the external camera or Gazebo.
        # -------------------------------------------------------------------------

        self.delta_angle = rospy.get_param("~delta_angle", self.delta_angle)
        self.delta_sample = rospy.get_param("~delta_sample", self.delta_sample)
        self.max_sample = rospy.get_param("~max_sample", self.max_sample)
        self.reached_distance = rospy.get_param("~reached_distance", self.reached_distance)
        self.slow_down_distance = rospy.get_param("~slow_down_distance", self.slow_down_distance)

        self.collision_margin = rospy.get_param("~collision_margin", 0.70)
        self.robot_self_filter_radius = rospy.get_param("~robot_self_filter_radius", 0.35)

        self.distance_error_weight = rospy.get_param("~distance_error_weight", 1.0)
        self.orientation_error_weight = rospy.get_param("~orientation_error_weight", 0.8)
        self.reverse_motion_penalty = rospy.get_param("~reverse_motion_penalty", 0.30)
        self.steering_penalty_weight = rospy.get_param("~steering_penalty_weight", 0.05)

        self.minimum_displacement_for_heading_update = rospy.get_param(
            "~minimum_displacement_for_heading_update",
            0.03
        )

        self.use_camera_localization = rospy.get_param("~use_camera_localization", True)
        self.use_ground_truth_fallback = rospy.get_param("~use_ground_truth_fallback", False)

        self.wait_for_ur5_signal = rospy.get_param("~wait_for_ur5_signal", False)
        self.navigation_enabled = not self.wait_for_ur5_signal

        #Variable initialization
        self.position = None
        self.theta = rospy.get_param("~initial_theta", 0.0)
        self.obstacles = []
        self.limits = None
        self.goal_reached = False #Wait until UR5 tells us to approach.

        #TODO Define other necessary variables.

        # -------------------------------------------------------------------------
        # BLOCK 2: Localization and waypoint state variables.
        # previous_camera_position is used to estimate theta from the displacement
        # between two consecutive camera detections.
        # -------------------------------------------------------------------------

        self.previous_camera_position = None
        self.camera_localization_received = False

        self.target_points = self.read_target_points_from_ros_params()
        self.current_target_index = 0

        #TODO Target position initialization. It is possible to consider several target points to maneuver and approach the UR5 robot.
        self.goal = copy.deepcopy(self.target_points[self.current_target_index])

        # Local target initialization to avoid errors until the first point is calculated.
        self.local_target = self.global2local(self.goal) if self.position is not None else copy.deepcopy(self.goal)
        self.local_path = [copy.deepcopy(self.local_target) for i in range(4)]

        print("Goal x: {}, y: {}".format(self.goal.x, self.goal.y))

        # TODO consider more subscribers/publishers if needed

        # -------------------------------------------------------------------------
        # BLOCK 3: Subscribers.
        # For the final assignment, the default localization source is /pose_array,
        # generated by object_localization.py from the external RGB-D camera.
        # Ground truth can be enabled only for debugging.
        # -------------------------------------------------------------------------

        if self.use_camera_localization:
            self.position_subscriber = rospy.Subscriber(
                "/pose_array",
                geometry_msgs.msg.PoseArray,
                self.position_callback,
                queue_size=1
            )
        else:
            self.position_subscriber = rospy.Subscriber(
                "/blue/ground_truth",
                Odometry,
                self.ground_truth_position_callback,
                queue_size=1
            )

        if self.use_ground_truth_fallback:
            self.ground_truth_fallback_subscriber = rospy.Subscriber(
                "/blue/ground_truth",
                Odometry,
                self.ground_truth_position_callback,
                queue_size=1
            )

        self.obstacles_subscriber = rospy.Subscriber(
            "/obstacles",
            sensor_msgs.msg.PointCloud2,
            self.obstacles_callback,
            queue_size=1
        )

        self.free_zone_subscriber = rospy.Subscriber(
            "/free_zone",
            sensor_msgs.msg.PointCloud2,
            self.limits_callback,
            queue_size=1
        )

        self.ur5_object_grasped_subscriber = rospy.Subscriber(
            "/ur5_object_grasped",
            std_msgs.msg.Bool,
            self.ur5_object_grasped_callback,
            queue_size=1
        )

        ## Publishers definition
        self.ackermann_command_publisher = rospy.Publisher(
            "/blue/ackermann_cmd",
            ackermann_msgs.msg.AckermannDrive,
            queue_size=10,
        )

        self.marker_publisher = rospy.Publisher(
            "/local_path",
            MarkerArray,
            queue_size=10,
        )

        self.blue_goal_reached_publisher = rospy.Publisher(
            "/blue_goal_reached",
            std_msgs.msg.Bool,
            queue_size=1,
            latch=True
        )

        rospy.loginfo("Camera localization enabled: %s", str(self.use_camera_localization))
        rospy.loginfo("Ground-truth fallback enabled: %s", str(self.use_ground_truth_fallback))
        rospy.loginfo("Waiting for UR5 signal before moving: %s", str(self.wait_for_ur5_signal))
        rospy.loginfo("Collision margin: %.3f m", self.collision_margin)
        rospy.loginfo("Target points: %s", self.target_points_to_string())

    # -------------------------------------------------------------------------
    # BLOCK 4: Target point parser.
    # The final goal can be given as _goal_x and _goal_y, or several waypoints
    # can be given as _target_points:="x1,y1;x2,y2".
    # -------------------------------------------------------------------------

    def read_target_points_from_ros_params(self):
        target_points = []
        target_points_string = rospy.get_param("~target_points", "")

        if target_points_string:
            raw_points = target_points_string.split(";")

            for raw_point in raw_points:
                clean_point = raw_point.strip()

                if not clean_point:
                    continue

                coordinates = clean_point.split(",")

                if len(coordinates) != 2:
                    rospy.logwarn("Invalid target point ignored: %s", clean_point)
                    continue

                target_point = geometry_msgs.msg.Point()
                target_point.x = float(coordinates[0])
                target_point.y = float(coordinates[1])
                target_point.z = 0.0
                target_points.append(target_point)

        if len(target_points) == 0:
            target_point = geometry_msgs.msg.Point()
            target_point.x = rospy.get_param("~goal_x", 5.0)
            target_point.y = rospy.get_param("~goal_y", 3.0)
            target_point.z = 0.0
            target_points.append(target_point)

        return target_points

    def target_points_to_string(self):
        points_as_text = []

        for point in self.target_points:
            points_as_text.append("({:.3f}, {:.3f})".format(point.x, point.y))

        return " -> ".join(points_as_text)

    #Callbacks

    #TODO modify this callback to not depend on the position given by Gazebo.

    # -------------------------------------------------------------------------
    # BLOCK 5: Camera-based BLUE localization.
    # object_localization.py publishes:
    #   pose_array.poses[0] -> red object
    #   pose_array.poses[1] -> BLUE robot
    #
    # The camera gives x and y. The yaw angle theta is approximated from the
    # displacement between the current and previous camera detections.
    # -------------------------------------------------------------------------

    def position_callback(self, pose_array):
        if len(pose_array.poses) < 2:
            return

        detected_robot_position = pose_array.poses[1].position

        if detected_robot_position.z < 0:
            return

        new_position = geometry_msgs.msg.Point()
        new_position.x = detected_robot_position.x
        new_position.y = detected_robot_position.y
        new_position.z = 0.0

        if self.previous_camera_position is not None:
            delta_x = new_position.x - self.previous_camera_position.x
            delta_y = new_position.y - self.previous_camera_position.y
            displacement = sqrt(delta_x * delta_x + delta_y * delta_y)

            if displacement >= self.minimum_displacement_for_heading_update:
                self.theta = atan2(delta_y, delta_x)

        self.previous_camera_position = copy.deepcopy(new_position)
        self.position = new_position
        self.camera_localization_received = True

    # -------------------------------------------------------------------------
    # BLOCK 6: Ground-truth callback for debugging.
    # The final practice solution can use the camera callback above. This callback
    # is kept to test navigation independently from camera segmentation.
    # -------------------------------------------------------------------------

    def ground_truth_position_callback(self, ground_truth):
        if self.use_camera_localization and self.camera_localization_received:
            return

        self.position = ground_truth.pose.pose.position

        orientation = ground_truth.pose.pose.orientation
        quaternion = [orientation.x, orientation.y, orientation.z, orientation.w]
        euler = tf_conversions.transformations.euler_from_quaternion(quaternion)
        self.theta = euler[2]

    def ur5_object_grasped_callback(self, message):
        if message.data:
            self.navigation_enabled = True
            rospy.loginfo("UR5 grasp signal received. BLUE navigation is now enabled.")

    def obstacles_callback(self, obstacles):
        pc_obstacles=pc2.read_points(obstacles, field_names=("x", "y", "z"), skip_nans=True)

        #Save as geometry_msg.Point
        self.obstacles=[]
        for point in pc_obstacles:
            x,y,z = point
            new_point = geometry_msgs.msg.Point(x,y,z)
            self.obstacles.append(new_point)

    def limits_callback(self, limits):
        pc_limits=pc2.read_points(limits, field_names=("x", "y", "z"), skip_nans=True)

        #Save as geometry_msg.Point
        self.limits=[]

        #Decrease the size of the point cloud to speed up the search.
        num_points = max(int(limits.width/18),0)
        count=0
        for point in pc_limits:
            if count==0:
                x,y,z = point
                new_point = geometry_msgs.msg.Point(x,y,z)
                self.limits.append(new_point)
                count=num_points
            else: count-=1

    # Calculate the control commands to reach the planned local target.
    def controlActionCalculation(self):
        # Detect if the trajectory is finished.
        if self.position is None or self.goal_reached:
            return

        if not self.navigation_enabled:
            self.publish_stop_command()
            rospy.loginfo_throttle(3.0, "Waiting for UR5 grasp signal before moving.")
            return
        
        ackermann_control=ackermann_msgs.msg.AckermannDrive()
        ackermann_control.speed, ackermann_control.steering_angle = 0.0, 0.0

        # Detect if the robot has reached the following target point.
        if self.distance(self.position, self.goal) < self.reached_distance:
            self.switch_to_next_target_or_finish()
            return
        
        # Reduce the veolicty when the robot is reaching the target.
        goal_distance = self.distance(self.position, self.goal) 
        if goal_distance - self.reached_distance < self.slow_down_distance:
            speed = MIN_SPEED
            #Set the target as local target.
            self.local_target=self.global2local(self.goal)
        else:
            speed=MAX_SPEED

        #Variable initialization
        min_error = 1000.0
        best_command_found = False

        # Check possible action control commands
        for steer in np.arange(-MAX_STEER_ANGLE, MAX_STEER_ANGLE+0.01, self.delta_angle):
            if abs(steer)<0.01:
                steer=0.0

            #Reduce the velocity when the turn is big.
            k_sp = (MAX_STEER_ANGLE-abs(steer))/MAX_STEER_ANGLE
            speed2 = max(speed*k_sp, MIN_SPEED)

            # Check forwards and backwards movement.
            directions = [-speed2, speed2]

            for dir in directions:
                flag_collision_risk = False

                #TODO Calculate turn radius and velocity using the robot kinematics.

                # -----------------------------------------------------------------
                # BLOCK 7: Bicycle model radius and angular velocity.
                # R = L / tan(delta)
                # omega = v / R
                # For a near-zero steering angle, the trajectory is approximated as
                # a straight line.
                # -----------------------------------------------------------------

                if abs(steer) < 0.0001:
                    turn_radius = None
                    angular_velocity = 0.0
                else:
                    turn_radius = VEHICLE_LENGHT / tan(steer)
                    angular_velocity = dir / turn_radius

                final_local_point = geometry_msgs.msg.Point()
                final_orientation = 0.0

                # Calculate the trajectory using the angle rotation. Several points are sampled from the trajectory over time, 
                # therefore the sample variable is equivalent to the t variable in the robot kinematic equation.
                for sample in np.arange(self.delta_sample, self.max_sample+0.01, self.delta_sample):
                    local_point=geometry_msgs.msg.Point()

                    #TODO calculate trajectory points using the robot kinematics.

                    # -----------------------------------------------------------------
                    # BLOCK 8: Candidate local trajectory generation.
                    # Required model:
                    # x = v * cos(omega * t) * t
                    # y = v * sin(omega * t) * t
                    # -----------------------------------------------------------------

                    if abs(angular_velocity) < 0.0001:
                        local_point.x = dir * sample
                        local_point.y = 0.0
                        local_point.z = 0.0
                        final_orientation = 0.0
                    else:
                        local_point.x = dir * cos(angular_velocity * sample) * sample
                        local_point.y = dir * sin(angular_velocity * sample) * sample
                        local_point.z = 0.0
                        final_orientation = angular_velocity * sample

                    final_local_point = copy.deepcopy(local_point)
                
                    #TODO Detect collisions risk.

                    # -----------------------------------------------------------------
                    # BLOCK 9: Collision risk detection.
                    # A trajectory is rejected if any sampled point gets closer than
                    # collision_margin to any detected obstacle point.
                    # -----------------------------------------------------------------

                    for obstacle in self.obstacles:
                        obstacle_distance_to_robot = sqrt(obstacle.x * obstacle.x + obstacle.y * obstacle.y)

                        if obstacle_distance_to_robot < self.robot_self_filter_radius:
                            continue

                        if self.distance(local_point, obstacle) <= self.collision_margin:
                            flag_collision_risk = True
                            break
                    
                    if flag_collision_risk:
                        break
 
                # If there is no collision, evaluate the trajectory.
                if not flag_collision_risk:

                    #TODO estimate the trajectory evaluation in terms of the distance and orientation error to self.local_target.

                    # -----------------------------------------------------------------
                    # BLOCK 10: Trajectory score.
                    # The trajectory is scored using:
                    #   1. distance from final trajectory point to the local target,
                    #   2. orientation error with respect to the local target,
                    #   3. a small penalty for reversing,
                    #   4. a small penalty for large steering angles.
                    # -----------------------------------------------------------------

                    distance_error = self.distance(final_local_point, self.local_target)

                    desired_heading = self.angle(self.local_target, final_local_point)
                    orientation_error = abs(self.normalize_angle(desired_heading - final_orientation))

                    reverse_penalty = 0.0
                    if dir < 0.0:
                        reverse_penalty = self.reverse_motion_penalty

                    steering_penalty = self.steering_penalty_weight * abs(steer) / MAX_STEER_ANGLE

                    error = (
                        self.distance_error_weight * distance_error +
                        self.orientation_error_weight * orientation_error +
                        reverse_penalty +
                        steering_penalty
                    )

                    if error < min_error:
                        min_error=error
                        best_command_found = True
                        ackermann_control.steering_angle=steer
                        ackermann_control.speed=dir
        
        #Publish message
        if not best_command_found:
            rospy.logwarn_throttle(1.0, "No collision-free trajectory found. Stopping BLUE robot.")
            ackermann_control.speed = 0.0
            ackermann_control.steering_angle = 0.0

        self.ackermann_command_publisher.publish(ackermann_control)

    #### Don't edit this function! ####
    # Trajectory planning towards the target while avoiding obstacles. It is executed at a lower frequency.
    ''' Code implemented from the following research article:
            OpenStreetMap-Based Autonomous Navigation With LiDAR Naive-Valley-Path Obstacle Avoidance
            Miguel Ángel Muñoz Bañón, Edison Velasco Sánchez, Francisco A. Candelas, Fernando Torres
            IEEE Transactions on Intelligent Transportation Systems, 2022
    '''
    def localGoalCalculation(self):
        if self.position is  None or self.goal_reached or self.limits is None:
            return

        if not self.navigation_enabled:
            return

        if len(self.limits) == 0:
            return

        #Parameter definition
        wa, wr, ar, aa = 100.0, 1.0, 0.8, 0.3
        min_force = wr / pow(0.1, ar) - wa / pow(100.0, aa) + 1000

        local_goal=geometry_msgs.msg.Point()
        self.local_path=[]
        min_distance = 10000.0
        goal_in_local_axis = self.global2local(self.goal)

        # 1) Trajectory points within the limited radius.
        for limit_point in self.limits:
            distance_a = self.distance(limit_point, goal_in_local_axis)
            if distance_a<0.1:
                distance_a=0.1

            force_a = wa / pow(distance_a,aa)

            #Computation of the minimum obstacle distance and its weight.
            min_distance=10000.0
            force_r = 0.0

            for obstacle_point in self.obstacles:
                distance_r = self.distance(limit_point,obstacle_point)
                if distance_r<0.1:
                    distance_r=0.1
                if distance_r<min_distance:
                    min_distance=distance_r
                    force_r = wr / pow(distance_r, ar)

            force = force_r - force_a

            if force < min_force:
                min_force=force
                local_goal=limit_point

        self.local_path.append(local_goal)

        # 2) Trajectory points with the inner rings.
        # Parameter definition.
        wa2 = 3.0
        wr2 = 1.0
        ar2 = 0.5
        aa2 = 0.3
        radious = 4.0
        delta_rad = radious / 3.0

        for rad in np.arange(radious, delta_rad-0.1, -delta_rad):
            min_force = wr / pow(0.1, ar) - wa / pow(100.0, aa) + 1000

            for limit_point in self.limits:
                depth, azimuth=self.cartesian2Spherical(limit_point.x, limit_point.y)
                p_in  = self.spherical2Cartesian(rad, azimuth)

                distance_a=self.distance(p_in, self.local_path[0])
                if distance_a<0.1:
                    distance_a=0.1
                force_a = wa2 /pow(distance_a,aa2)

                min_distance = 10000.0
                force_r = 0.0

                for obstacle_point in self.obstacles:
                    distance_r = self.distance(p_in, obstacle_point)
                    if distance_r<0.1:
                        distance_r=0.1
                    if distance_r<min_distance:
                        min_distance=distance_r
                        force_r = wr2 / pow(distance_r, ar2)

                force = force_r-force_a
                if force < min_force:
                    min_force=force
                    local_goal=p_in

            self.local_path.append(local_goal)

        if len(self.local_path) >= 2:
            self.local_target = self.local_path[-2]
        else:
            self.local_target = self.global2local(self.goal)

        #Publish the target visualization.
        marker_msg = MarkerArray()
        for id, point in enumerate(self.local_path):
            marker = Marker()
            marker.header.frame_id = "blue/velodyne"
            marker.header.stamp = rospy.Time()
            marker.id = id
            marker.type = Marker.SPHERE
            marker.action = Marker.ADD
            marker.pose.position = point
            marker.pose.orientation.w = 1.0
            marker.scale.x = 0.5
            marker.scale.y = 0.5
            marker.scale.z = 0.5
            marker.color.a = 1.0
            marker.color.r = 1.0
            marker.color.g = 0.0
            marker.color.b = 1.0
            marker_msg.markers.append(marker)

        self.marker_publisher.publish(marker_msg)

    # -------------------------------------------------------------------------
    # BLOCK 11: Goal management.
    # If several target points are defined, the robot switches to the next one.
    # Otherwise, it stops and publishes /blue_goal_reached.
    # -------------------------------------------------------------------------

    def switch_to_next_target_or_finish(self):
        if self.current_target_index + 1 < len(self.target_points):
            self.current_target_index += 1
            self.goal = copy.deepcopy(self.target_points[self.current_target_index])
            self.local_target = self.global2local(self.goal)

            rospy.loginfo(
                "Intermediate goal reached. Switching to next goal x=%.3f, y=%.3f",
                self.goal.x,
                self.goal.y
            )

            return

        print("Goal reached")
        self.goal_reached=True
        self.publish_stop_command()
        self.blue_goal_reached_publisher.publish(std_msgs.msg.Bool(data=True))

    def publish_stop_command(self):
        ackermann_control = ackermann_msgs.msg.AckermannDrive()
        ackermann_control.speed = 0.0
        ackermann_control.steering_angle = 0.0
        self.ackermann_command_publisher.publish(ackermann_control)
    
    def distance(self, p1:geometry_msgs.msg.Point, p2:geometry_msgs.msg.Point):
        return sqrt((p1.x-p2.x)**2+(p1.y-p2.y)**2)
    
    # Angle from point p2 to p1
    def angle(self, p1:geometry_msgs.msg.Point, p2:geometry_msgs.msg.Point):
        return atan2((p1.y-p2.y),p1.x-p2.x)

    def normalize_angle(self, angle):
        while angle > pi:
            angle -= 2.0 * pi

        while angle < -pi:
            angle += 2.0 * pi

        return angle
    
    #Transformation from global to local position
    def global2local(self, p:geometry_msgs.msg.Point):
        result = geometry_msgs.msg.Point()

        if self.position is None:
            result.x = p.x
            result.y = p.y
            result.z = 0.0
            return result

        #Translation
        x = (p.x-self.position.x) 
        y = (p.y-self.position.y)

        #Rotation
        result.x = x * cos(-self.theta) - y * sin(-self.theta)
        result.y = x * sin(-self.theta) + y * cos(-self.theta)
        result.z = 0.0
        return result
    
    #From spherical to cartesian coordinates
    def spherical2Cartesian(self, depth, azimuth):
        sin_azimuth = sin(azimuth)
        cos_azimuth = cos(azimuth)
        p=geometry_msgs.msg.Point()
        p.x = depth * cos_azimuth
        p.y = depth * sin_azimuth
        p.z = 0.0
        return p
    
    #From cartesian to spherical coordinates
    def cartesian2Spherical(self, x,  y):
        depth = sqrt((x * x) + (y * y))

        azimuth = atan2(y, x)

        if (azimuth < 0): azimuth += 2*pi
        if (azimuth >= 2*pi): azimuth -= 2*pi

        return depth, azimuth
    
    def run(self):
        #Control loop
        rate = rospy.Rate(self.rate)
        count=3
        while not rospy.is_shutdown():
            self.controlActionCalculation()
            if count==0:
                self.localGoalCalculation()
                count=3
            else:
                count-=1
            rate.sleep()


def main():
    try:
        print("Init blue_planner_node")
        node = BlueTrajectoryPlanner()
        node.run()
        
    except rospy.ROSInterruptException:
        return
    except KeyboardInterrupt:
        return


if __name__ == "__main__":
    main()